---
- name: fishの設定ファイルを配置
  copy:
    src: files/
    dest: "{{ ansible_env.HOME }}/.config/fish/"
  notify: fisher_update

- name: fishリポジトリを追加
  become: yes
  apt_repository:
    repo: ppa:fish-shell/release-3

- name: fishをインストール
  become: yes
  apt:
    name: fish

- name: fishをデフォルトシェルに設定
  user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/fish

- name: fzfの存在確認
  stat:
    path: '{{ ansible_env.HOME }}/.fzf'
  register: fzf_command

- name: fzfをgitからクローン
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: '{{ ansible_env.HOME }}/.fzf'
    depth: 1
  when: not fzf_command.stat.exists

- name: fzfをインストール
  shell: fish -c "{{ ansible_env.HOME }}/.fzf/install"
  when: not fzf_command.stat.exists
