---
- name: fishのパスを取得
  command: which fish
  register: fish_path
  changed_when: false

- name: fishをデフォルトシェルに設定
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ fish_path.stdout }}"

- name: fishの設定ファイルを配置
  copy:
    src: files/
    dest: "{{ ansible_user_dir }}/.config/fish/"
  notify: fisher_update
