---
- name: Add Fish PPA and install Fish shell
  apt_repository:
    repo: ppa:fish-shell/release-3
    state: present

- name: Install Fish shell
  apt:
    name: fish
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Set Fish as default shell
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/fish

- name: Install fzf
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: '{{ ansible_env.HOME }}/.fzf'
    depth: 1

- name: Run fzf install script
  command: "{{ ansible_env.HOME }}/.fzf/install --all"
  args:
    executable: /usr/bin/fish

- name: Install Fisher for Fish shell
  command: fish -c "curl -sL git.io/fisher | source && fisher update"
  changed_when: false
