---
- name: fishの設定ファイルを配置
  copy:
    src: files/
    dest: "{{ ansible_env.HOME }}/.config/fish/"

- name: fishリポジトリを追加
  apt_repository:
    repo: ppa:fish-shell/release-3
    state: present

- name: fishをインストール
  apt:
    name: fish
    state: present

- name: fishをデフォルトシェルに設定
  user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/fish

- name: fzfをgitからクローン
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: '{{ ansible_env.HOME }}/.fzf'
    depth: 1

- name: fzfをインストール
  command: "{{ ansible_env.HOME }}/.fzf/install"
  args:
    executable: /usr/bin/fish

- name: fisherをインストール
  command: curl -sL git.io/fisher | source && fisher update
  args:
    executable: /usr/bin/fish
