#!/usr/bin/env bash

set -eu

DOTFILES=$HOME/dotfiles

if [ -z "$(which sudo)" ]; then
  echo "# sudoコマンドのインストール"
  apt install -y sudo
fi

echo "# sources.listを編集"
sudo sed -i.bak \
  -e "s|http://archive.ubuntu.com|http://jp.archive.ubuntu.com|g" \
  /etc/apt/sources.list
sudo apt update

if [ ! -d "$DOTFILES" ]; then
  if [ -z "$(which git)" ]; then
    sudo apt install -y git
  fi
  echo "# dotfilesをクローン"
  git clone https://github.com/mkizka/dotfiles "$DOTFILES"
else
  echo "# dotfilesをアップデート"
  cd "$DOTFILES"
  git pull
  cd -
fi

echo "# \$HOMEに置くファイルをコピー"
cp -afT "$DOTFILES"/home "$HOME"

if [ -n "$(which wslpath)" ] && [ -n "$(which wslvar)" ]; then
  echo "# WSL関連ファイルのコピーと設定"
  USERPROFILE="$(wslvar USERPROFILE)"
  if [ -n "$USERPROFILE" ]; then # Remote Containerでまれに取れない
    USERPROFILE="$(echo $USERPROFILE | tr " " "\n" | tail -n 1)" # distrodで出るエラー文を除去
    WINHOME="$(wslpath $USERPROFILE)"
    echo "# \$WINHOME: $WINHOME"
    # .wslconfigはWindows側にのみ置く
    cp -f "$DOTFILES"/wsl/.wslconfig "$WINHOME"/
    # wsl.confはWSL側にのみ置く
    sudo cp -f "$DOTFILES"/wsl/wsl.conf /etc/wsl.conf
    # WSLでWindowsの認証情報を使用する
    # https://qiita.com/snaka/items/cc83553a81e00b2d26f3
    git config --global credential.helper "${WINHOME}/scoop/apps/git/current/mingw64/libexec/git-core/git-credential-manager-core.exe"
  else
    echo "# エラー: USERPROFILEの値が取得できませんでした"
  fi
else 
  echo "# WSL関連の処理をスキップ"
fi

if [ -z "$(which fish)" ]; then
  echo "# fishのインストール"
  # tzdataの対話を無視
  sudo DEBIAN_FRONTEND=noninteractive apt install -y software-properties-common
  sudo apt-add-repository -y ppa:fish-shell/release-3
  sudo apt update
  sudo apt install -y fish
fi

echo "# fisherでプラグインを更新"
mkdir -p ~/.config/fish
cp "$DOTFILES"/fish/fish_plugins ~/.config/fish/
fish -c "curl -sL git.io/fisher | source && fisher update"

if [ "$(tail -n 1 ~/.bashrc)" != "exec fish" ]; then
  echo "# ~/.bashrc末尾にexec fish追加"
  echo "exec fish" >> ~/.bashrc
fi

echo "# シェルの再起動"
exec "$SHELL" -l
