#!/usr/bin/env bash

set -e

WINHOME="$(wslpath "$(wslvar USERPROFILE)")"

files=(.vimrc .gitconfig .gitignore_global)

cd $HOME
for file in "${files[@]}"
do
  cp -f dotfiles/$file $HOME/
  cp -f dotfiles/$file $WINHOME/
done

# .wslconfigはWindows側にのみ置く
cp -f dotfiles/.wslconfig $WINHOME/

# wsl.confはWSL側にのみ置く
sudo cp -f dotfiles/wsl.conf /etc/wsl.conf

# WSLでWindowsの認証情報を使用する
# https://qiita.com/snaka/items/cc83553a81e00b2d26f3
git config --global credential.helper "${WINHOME}/scoop/apps/git/current/mingw64/libexec/git-core/git-credential-manager-core.exe"
