---
- hosts: localhost
  tasks:
    - name: resolv.conf更新
      become: true
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 8.8.8.8

    - name: sources.listの向き先を日本に変更
      become: true
      ansible.builtin.replace:
        path: /etc/apt/sources.list.d/ubuntu.sources
        regexp: http:\/\/archive\.ubuntu\.com\/ubuntu\/
        replace: https://ftp.udx.icscoe.jp/Linux/ubuntu/
        backup: true

    - name: build-essentialをインストール
      become: true
      ansible.builtin.apt:
        name: build-essential
        update_cache: true

    # zsh
    - name: zshのパスを取得
      ansible.builtin.command: which zsh
      register: zsh_path
      changed_when: false

    - name: zshをデフォルトシェルに設定
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: "{{ zsh_path.stdout }}"

    # mise
    - name: miseで管理しているツールをインストール
      ansible.builtin.command: mise install --jobs 1
      changed_when: false

    # wsl
    - name: WSLかどうかを確認
      ansible.builtin.stat:
        path: /usr/bin/wslpath
      register: wslpath

    - when: wslpath.stat.exists
      block:
        - name: wsluをインストール
          become: true
          ansible.builtin.apt:
            name: wslu

        - name: Windows側のホームディレクトリのパスを取得
          ansible.builtin.shell: wslpath "$(wslvar USERPROFILE)"
          register: windows_home
          changed_when: false

        - ansible.builtin.debug:
            var: windows_home.stdout

        # .wslconfigはWSLが起動するタイミングで読み込まれるためシンボリックリンクが使えない
        - name: .wslconfigをコピー
          ansible.builtin.copy:
            src: "{{ ansible_user_dir }}/.config/wsl/.wslconfig"
            dest: "{{ windows_home.stdout }}/.wslconfig"

        - name: wsl.confのシンボリック作成
          become: true
          ansible.builtin.file:
            src: "{{ ansible_user_dir }}/.config/wsl/wsl.conf"
            dest: /etc/wsl.conf
            state: link
            force: true
