---
- name: miseの設定ファイルを配置
  copy:
    src: files/
    dest: "{{ ansible_env.HOME }}/.config/mise/"

- name: miseのインストール
  shell: curl https://mise.jdx.dev/install.sh | sh

- name: mise install実行
  command: '{{ ansible_env.HOME }}/.local/bin/mise install -y'
