---
- name: WSLかどうかを確認
  stat:
    path: /usr/bin/wslpath
  register: wsllpath

- when: wsllpath.stat.exists
  block:
    - name: wsluをインストール
      become: true
      apt:
        name: wslu

    - name: Windows側のホームディレクトリのパスを取得
      shell: wslpath "$(wslvar USERPROFILE)"
      register: windows_home
      changed_when: false

    - debug:
        var: windows_home.stdout

    - name: .wslconfigをコピー
      become: true
      copy:
        src: files/.wslconfig
        dest: "{{ windows_home.stdout }}/"

    - name: wsl.confをコピー
      become: true
      copy:
        src: files/wsl.conf
        dest: '/etc/wsl.conf'
