---
- name: sources.listの向き先を日本に変更
  become: true
  replace:
    path: /etc/apt/sources.list
    regexp: 'http://archive.ubuntu.com'
    replace: 'http://jp.archive.ubuntu.com'
    backup: true

- name: よく使うパッケージをインストール
  become: true
  apt:
    name:
      - git
      - vim
    update_cache: true

- name: ホームディレクトリに配置するファイルをコピー
  copy:
    src: files/
    dest: "{{ ansible_user_dir }}/"
