[tools]
deno = "latest"
go = "latest"
java = "temurin-17"
node = "lts"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:ccusage" = "latest"
python = "3.13.3"
rust = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]

