name: "ShellCheck and Depoy"

on:
  push:
    branches:
      - main

jobs:
  shellcheck:
    name: "ShellCheck"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ludeeus/action-shellcheck@master
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: [shellcheck]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: mkizka
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: mkizka/dotfiles:latest
          cache-from: type=registry,ref=mkizka/dotfiles:latest
          cache-to: type=inline
